package nl.hanze.se4.automaat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarReviewAllPropertiesEquals(CarReview expected, CarReview actual) {
        assertCarReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertCarReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarReviewAllUpdatablePropertiesEquals(CarReview expected, CarReview actual) {
        assertCarReviewUpdatableFieldsEquals(expected, actual);
        assertCarReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarReviewAutoGeneratedPropertiesEquals(CarReview expected, CarReview actual) {
        assertThat(actual)
            .as("Verify CarReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarReviewUpdatableFieldsEquals(CarReview expected, CarReview actual) {
        assertThat(actual)
            .as("Verify CarReview relevant properties")
            .satisfies(a -> assertThat(a.getReview()).as("check review").isEqualTo(expected.getReview()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarReviewUpdatableRelationshipsEquals(CarReview expected, CarReview actual) {
        assertThat(actual)
            .as("Verify CarReview relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()))
            .satisfies(a -> assertThat(a.getCar()).as("check car").isEqualTo(expected.getCar()));
    }
}
