package nl.hanze.se4.automaat.domain;

import static nl.hanze.se4.automaat.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class InspectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionAllPropertiesEquals(Inspection expected, Inspection actual) {
        assertInspectionAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionAllUpdatablePropertiesEquals(Inspection expected, Inspection actual) {
        assertInspectionUpdatableFieldsEquals(expected, actual);
        assertInspectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionAutoGeneratedPropertiesEquals(Inspection expected, Inspection actual) {
        assertThat(actual)
            .as("Verify Inspection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionUpdatableFieldsEquals(Inspection expected, Inspection actual) {
        assertThat(actual)
            .as("Verify Inspection relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getOdometer()).as("check odometer").isEqualTo(expected.getOdometer()))
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPhoto()).as("check photo").isEqualTo(expected.getPhoto()))
            .satisfies(a -> assertThat(a.getPhotoContentType()).as("check photo contenty type").isEqualTo(expected.getPhotoContentType()))
            .satisfies(a ->
                assertThat(a.getCompleted())
                    .as("check completed")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCompleted())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionUpdatableRelationshipsEquals(Inspection expected, Inspection actual) {
        assertThat(actual)
            .as("Verify Inspection relationships")
            .satisfies(a -> assertThat(a.getCar()).as("check car").isEqualTo(expected.getCar()))
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getRental()).as("check rental").isEqualTo(expected.getRental()));
    }
}
