package nl.hanze.se4.automaat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RouteFromToAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteFromToAllPropertiesEquals(RouteFromTo expected, RouteFromTo actual) {
        assertRouteFromToAutoGeneratedPropertiesEquals(expected, actual);
        assertRouteFromToAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteFromToAllUpdatablePropertiesEquals(RouteFromTo expected, RouteFromTo actual) {
        assertRouteFromToUpdatableFieldsEquals(expected, actual);
        assertRouteFromToUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteFromToAutoGeneratedPropertiesEquals(RouteFromTo expected, RouteFromTo actual) {
        assertThat(actual)
            .as("Verify RouteFromTo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteFromToUpdatableFieldsEquals(RouteFromTo expected, RouteFromTo actual) {
        assertThat(actual)
            .as("Verify RouteFromTo relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteFromToUpdatableRelationshipsEquals(RouteFromTo expected, RouteFromTo actual) {
        assertThat(actual)
            .as("Verify RouteFromTo relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
