package nl.hanze.se4.automaat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RouteStopAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopAllPropertiesEquals(RouteStop expected, RouteStop actual) {
        assertRouteStopAutoGeneratedPropertiesEquals(expected, actual);
        assertRouteStopAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopAllUpdatablePropertiesEquals(RouteStop expected, RouteStop actual) {
        assertRouteStopUpdatableFieldsEquals(expected, actual);
        assertRouteStopUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopAutoGeneratedPropertiesEquals(RouteStop expected, RouteStop actual) {
        assertThat(actual)
            .as("Verify RouteStop auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopUpdatableFieldsEquals(RouteStop expected, RouteStop actual) {
        assertThat(actual)
            .as("Verify RouteStop relevant properties")
            .satisfies(a -> assertThat(a.getNr()).as("check nr").isEqualTo(expected.getNr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopUpdatableRelationshipsEquals(RouteStop expected, RouteStop actual) {
        assertThat(actual)
            .as("Verify RouteStop relationships")
            .satisfies(a -> assertThat(a.getRouteFromTo()).as("check routeFromTo").isEqualTo(expected.getRouteFromTo()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
